# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundNAV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('nav', models.DecimalField(decimal_places=6, max_digits=20)),
                ('mf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigator.MutualFund')),
            ],
        ),
    ]
