# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc',
            name='amcname',
            field=models.CharField(default='Unnamed AMC', max_length=100),
        ),
    ]
