# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-07 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0002_amc_amcname'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundStaticJSON',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('navigator.mutualfund',),
        ),
        migrations.AlterField(
            model_name='mutualfundnav',
            name='nav',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=20),
        ),
        migrations.AlterIndexTogether(
            name='mutualfundnav',
            index_together=set([('date', 'nav')]),
        ),
    ]
